### ISSUE TITLE
Incorrect instance passed to method 

### ISSUE THREAD

**Issue by matwright** [zfcampus/zf-mvc-auth#79]
Factory/DefaultAuthenticationListenerFactory.php

```php
 $oauth2Server = $this->createOAuth2Server($services);

        if ($oauth2Server) {
            $listener->setOauth2Server($oauth2Server);
        }
```

In version 1.0.3 the createOAuthServer returns an instance of ZF\OAuth2\Factory\OAuth2ServerInstanceFactory whereas the setOauth2Server method requires an instance of OAuth2\Server.

Authentication\DefaultAuthenticationListener.php

```php
public function setOauth2Server(OAuth2Server $oauth2Server) 
```

The Listener has been rewritten in later versions of zf-mvc-auth, however zf-apigility/composer.json dev-master still references version 1.0.0 and overriding zf-mvc-auth version in composer results in conflicts.

It would we good if we could just add a verification on the $oauth2Server type and if a OAuth2ServerInstanceFactory object  then invoke it to ensure the correct OAuth2\Server object is passed onto the setOauth2Server method:

https://github.com/matwright/zf-mvc-auth/blob/1.0.4-branch/src/Factory/DefaultAuthenticationListenerFactory.php#L38

Error for reference/

Argument 1 passed to ZF\MvcAuth\Authentication\DefaultAuthenticationListener::setOauth2Server() must be an instance of OAuth2\Server, instance of ZF\OAuth2\Factory\OAuth2ServerInstanceFactory given, called in /vendor/zfcampus/zf-mvc-auth/src/Factory/DefaultAuthenticationListenerFactory.php on line 41 and defined

**Comment by SvenRtbg** [comment]
> It would we good if we could just add a verification on the $oauth2Server type and if a OAuth2ServerInstanceFactory object then invoke it to ensure the correct OAuth2\Server object is passed onto the setOauth2Server method:

Sorry, but your suggestion absolutely makes no sense. Having a method that instantiates a new Oauth2Server object, and declares to return such type, under all circumstances MUST return that object. If not, it is a bug that should be fixed, but never worked around like that.

**Comment by matwright** [comment]
@SvenRtbg the method createOAuth2Server does not return the object it is declared to return.
It is declared to return a OAuth2\Server object or bool false. However in the case I document above, it returns an ZF\OAuth2\Factory\OAuth2ServerInstanceFactory object. So docblock return type is incorrect.

Either the method should return type should include OAuth2ServerInstanceFactory and then a verfication is applied as per comment (its not good practice I know its just an attempt to get the function working) or if it is a bug then it needs pushing upstream to the dependancy (I thinks its Oauth module from memory) but I doubt very much that that will happen any time soon.

**Comment by SvenRtbg** [comment]
There are 4 return statements in the createOAuth2Server() method. Two return false, one returns the result of "new Oauth2Server()" (an alias to \Oauth2\Server), and the last one returns the result of the service manager when asked for $services->get('ZF\OAuth2\Service\OAuth2Server'), if present.

If this doesn't return an instance of Oauth2\Server, then the service manager is incorrectly configured. Can you provide a short code example that reproduces the problem? What is configured for this key in your service manager?

**Comment by matwright** [comment]
To take this further, the actual call that results in returning an object of an incorrect type is here:

https://github.com/zfcampus/zf-mvc-auth/blob/d9a834f46f68224019d3433e6bcb6ffb090a11ff/src/Factory/DefaultAuthenticationListenerFactory.php#L90

```php
        // If the service locator already has a pre-configured OAuth2 server, use it
        if ($services->has('ZF\OAuth2\Service\OAuth2Server')) {
            return $services->get('ZF\OAuth2\Service\OAuth2Server');
        }
```

The ZF\OAuth2\Service\OAuth2Server is configured within the zf-oauth2 module and returns the object of type ZF\OAuth2\Factory\OAuth2ServerFactory. Either way there is a lack of type checking and the result is that this module is not currently useable with the oauth module.

The type check could alternatively be applied to the above code:

```php
        // If the service locator already has a pre-configured OAuth2 server, use it
        if ($services->has('ZF\OAuth2\Service\OAuth2Server') && $services->get('ZF\OAuth2\Service\OAuth2Server') instanceof OAuth2\Server) {
            return $services->get('ZF\OAuth2\Service\OAuth2Server');
        }
```

Again its not pretty at all, but it is a workaround to at least get this module working with zf-oauth2.

**Comment by matwright** [comment]
My above comment was posted before reading your own comment.

To answer your question, the service is configured within the zf-oauth2 module:

```php
 'ZF\OAuth2\Service\OAuth2Server'  => 'ZF\OAuth2\Factory\OAuth2ServerFactory'
```
and the ZF\OAuth2\Factory\OAuth2ServerFactory class returns an object of type ZF\OAuth2\Factory\OAuth2ServerInstanceFactory

**Comment by SvenRtbg** [comment]
I've looked at this: What a mess... For some unexplained reason, that zf-oauth2 module returns a factory object instead of the really needed instance - probably to improve performance or something.

If it is true that the service manager of zf-oauth2 will always return a factory object when asked for 'ZF\OAuth2\Service\OAuth2Server', then your patch is wrong. Fix the function createOAuth2Server() to correctly unpack the real object from the factory and return it.

**Comment by matwright** [comment]
@SvenRtbgYes that is what I have been telling you all along ! And your 'fix the function...' is also what I suggested in my previous post .
Could you please create a new branch and I'll patch and send a PR right away.
You'll need to create the branch off the last 1.x commit as this is a version 1x issue as explained in my first comment. Thanks.

**Comment by matwright** [comment]
Here is a fix:

https://github.com/matwright/zf-mvc-auth/blob/hotfix/oauth2/src/Factory/DefaultAuthenticationListenerFactory.php#L93

If a Service is already being managed with this key, we check the type, if it is a OAuth2ServerInstanceFactory the object is __invoked to ensure we get the correct OAuth2Server object.

**Comment by SvenRtbg** [comment]
Here's the commit that broke the interface contract between zfcampus/zf-mvc-auth and zfcampus/zf-oauth2: https://github.com/weierophinney/zf-oauth2/commit/1eea5a1512419d350ad288bf3a25bcbdecfd9764

@matwright I still don't understand your initial comment:
> however zf-apigility/composer.json dev-master still references version 1.0.0 and overriding zf-mvc-auth version in composer results in conflicts.

This confuses me because if zf-mvc-auth 1.0.0 would be referenced, then the problem with 1.0.3 would not happen. The bug was introduced with zf-oauth2 version 1.1.1, which wasn't a bugfix, but an interface incompatible change (if you count the service manager configuration to be an interface). Where is the code you are using with that reference from?

zf-mvc-auth version | references zf-oauth2 | works with zf-oauth2 | breaks with zf-oauth2
-------------------------|----------------------------|---------------------------|----------------------------
1.0.0 to 1.0.2 | ~1.0 | 1.0.0 and up | none
1.0.3 | ~1.0 | up to 1.1.0 | 1.1.1 or later
1.1.0 | ~1.1 | 1.1.0 | 1.1.1 or later
1.1.1 | ^1.1.1 | 1.1.1 and later | -

The change in zf-oauth2 shouldn't have happened as a bug fix. It was an incompatible change and should have been tagged as version 2.0.0 of zf-oauth2.

**Comment by matwright** [comment]
@SvenRtbg  Yes sorry my comment should have read version ~1.0 not 1.0.0

So as you confirm in the table above, the break occurs with v 1.0.3 of zf-mvc-auth because the ~1.0 ref for zf-oauth will require the next significant release version, in my case when running composer in v 1.0.3 this installs zfcampus/zf-oauth2 v 1.1.2 and hence the break.

So this may just be an issue with the composer config in v 1.0.3. Instead of zf-oauth2 : ~1.0 it should be zf-oauth2 : <1.1.1 to avoid the break.

I will test and confirm.

**Comment by matwright** [comment]
@SvenRtbg I believe we need a version 1.0.4 of zf-mvc-auth which constrains the version of zf-oauth to less than 1.1.1 in composer. This resolves the BC break.

**Comment by matwright** [comment]
@SvenRtbg I'm going to close this, given the info you have left above, I'm going to work around the issue  otherwise. I'm caught up in the v1.0.3 break because of a separate ongoing issue with zf-oauth module also. I will deal with it otherwise.

**Comment by SvenRtbg** [comment]
You can add a dependency that restricts the choices of Composer to the `composer.json` of your project.

    "require": {
        "zfcampus/zf-oauth2": "<1.1.1",
        ....
    }

This will be evaluated in addition to the constraints of all the other packages. So if zf-mvc-auth 1.0.3 allows ~1.0 (which includes the broken versions), this would fix it by disallowing the broken versions. A slightly better approach would be to even go one step down in the version history and require `~1.0.0` of zf-oauth2. This would allow bugfixes in the 1.0 series, because it won't install the 1.1.0 version as the last allowed one (and I bet the reason for 1.1.1 and up to exist is bug fixes).

**Comment by matwright** [comment]
thanks @SvenRtbg yes that is what I've done, it's further complicated though because of an ongoing issue with the zf-oauth module, but thats another story. Thanks for your help.

**Comment by weierophinney** [comment]
@SvenRtbg and @matwright The change that was made was done to support the possibility of per-API (vs per-application) authentication. In the case of per-API authentication, we need to be able to pass information to the factory creating the instance, which necessitated changing this particular factory to return a factory instead of an instance.

If you have overridden the service to invoke your own factory, all you need to do is change your factory to return a closure that will return the server instance (instead of returning the server instance itself):

```php
class MyOAuth2ServerFactory
{
    public function __invoke($services)
    {
        // If before you did this:
        // return new OAuth2\Server();
        // now you would do this:
        return function () {
            return OAuth2\Server();
        };
    }
}
```

This was a necessary BC break to allow existing zf-oauth2 config to work alongside the updated zf-oauth2/zf-mvc-auth combination. We should have messaged it better.
